general_services = {
    'appointment':'/appointment/api/appointment/appointment/',
    'appointment_parameters':'/appointment/api/appointment/appointmentParameters/',
    'appointment_schedules':'/appointment/api/appointment/appointmentSchedules/',
    'appointment_status':'/appointment/api/appointment/appointmentStatus/',
    'appointment_template':'/appointment/api/appointment/appointmentTemplate/',
    'appointment_type': '/appointment/api/appointment/appointmentType/',
    'asn':"/appointment/api/appointment/asn/",
    'calendar_definition':'/appointment/api/Schedule/calendarDefinition',
    'calendar_schedule':'/appointment/api/Schedule/calendarSchedule',
    'calendar_schedule_utilization':'/appointment/api/Schedule/calendarScheduleUtilization',
    'calendar_window':'/appointment/api/Schedule/calendarWindow',
    'calendar_window_capacity':'/appointment/api/Schedule/calendarWindowCapacity',
    'calendar_window_capacity_type':'/appointment/api/Schedule/calendarWindowCapacityType',
    'capacity_constraint_type':'/appointment/api/appointment/capacityConstraintType',
    'climate_control':'/appointment/api/appointment/climateControl/',
    'content_type':'/appointment/api/appointment/contentType/',
    'day_level_capacity':'/appointment/api/appointment/dayLevelCapacity/',
    'day_level_scope':'/appointment/api/appointment/dayLevelScope/',
    'days_of_week':'/appointment/api/appointment/daysOfWeek/',
    'facility_capacities':"/appointment/api/appointment/facilityCapacities/",
    'facility_day_level_capacities':"/appointment/api/appointment/facilityDayLevelCapacity/",
    'facility_day_level_scope':"/appointment/api/appointment/facilityDayLevelScope/",
    'po': '/appointment/api/appointment/purchaseOrder/',
    'preference': '/appointment/api/scoring/preference/',
    'preference_attribute': '/appointment/api/scoring/preferenceAttribute/',
    'preference_type': '/appointment/api/scoring/preferenceType/',
    'priority': '/appointment/api/scoring/priority/',
    'product_class': '/appointment/api/appointment/productClass/',
    'resource_capacities': '/appointment/api/appointment/resourceCapacities/',
    'resource_group': '/appointment/api/appointment/resourceGroup/',
    'resource_group_status': '/appointment/api/appointment/resourceGroupStatus/',
    'resource_type': '/appointment/api/scoring/resourceType/',
    'resource_unit': '/appointment/api/appointment/resourceUnit/',
    'schedule': '/appointment/api/appointment/schedule/',
    'time_interval_capacity': '/appointment/api/appointment/timeIntervalCapacity/',
    'time_interval_definition': '/appointment/api/appointment/timeIntervalDefinition/',
    'time_interval_scope': '/appointment/api/appointment/timeIntervalScope/',
}