common_general_services = {
    'application_parm':'/api/idempotency/applicationParameter/',
    'assigned_instruction': '/api/fw-aux-svcs/assignedInstruction/',
    'assigned_questionnaire': '/api/fw-aux-svcs/assignedQuestionnaire/',
    'assigned_questionnaire_status': '/api/fw-aux-svcs/assignedQuestionnaireStatus/',
    'assigned_service_source': '/api/fw-aux-svcs/assignedServiceSource/',
    'assigned_service_status': '/api/fw-aux-svcs/assignedServiceStatus/',
    'assigned_services': '/api/fw-aux-svcs/assignedService/',
    'attribute_labels_config': '/api/fwcore/attributeLabelsConfig/',
    'audit_strategy': '/api/eventProducer/auditStrategy/',
    'available_attribute': '/api/rules/availableAttribute/',
    'available_entity': '/api/rules/availableEntity/',
    'available_entity_lookup': '/api/rules/availableEntityLookup/',
    'config_group_xref': '/api/standardconfig/configGroupXref/',
    'config_rule_group_xref': '/api/standardconfig/configRuleGroupXref/',
    'entity_label_key': '/api/tags/entityLabelKey/',
    'error_message': '/api/errorHandler/errorMessage/',
    'error_override': '/api/errorHandler/errorOverride/',
    'event_action': '/api/eventProducer/eventAction/',
    'event_action_details': '/api/eventProducer/eventActionDetails/',
    'event_strategy': '/api/eventProducer/eventStrategy/',
    'extension_handler': '/api/ServiceDefinition/extensionHandler/4',
    'extension_point': '/api/ServiceDefinition/extensionPoint/',
    'import_template':'/api/importtemplate/importTemplate/',
    'inbound_message_type': '/api/ServiceDefinition/inBoundMessageType/',
    'inheritance_meta_info': '/api/tags/inheritanceMetaInfo/',
    'inheritance_rules_header': '/api/tags/inheritanceRulesHeader/',
    'inheritance_strategy': '/api/tags/inheritanceStrategy/',
    'job_schedule': '/api/batch/jobSchedule/',
    'labels': '/api/tags/labels/',
    'nextup_config': '/api/nextup/nextUpConfiguration/',
    'outbound_message_type': '/api/ServiceDefinition/outBoundMessageType/',
    'pipelines' : '/api/ServiceDefinition/pipeline/',
    'reason_code_override_type':'/api/errorHandler/reasonCodeOverrideType',
    'response_template': '/api/fwcore/responseTemplate/',
    'resources': '/api/fworganization/resources/',
    'rule':'/api/rules/rule/',
    'rule_action':'/api/rules/ruleAction/',
    'rule_condition':'/api/rules/ruleCondition/',
    'rule_group':'/api/rules/ruleGroup/',
    'rule_group_rule_type_xref':'/api/rules/ruleGroupRuleTypeXref/',
    'rule_type_avail_attr_xref':'/api/rules/ruleTypeAvailableAttributeXref/',
    'rule_type_avail_entity_xref':'/api/rules/ruleTypeAvailableEntityXref/',
    'schema_converter':'/api/ServiceDefinition/schemaConverter/',
    'schema_definition':'/api/ServiceDefinition/schemaDefinition/',
    'service_definition':'/api/ServiceDefinition/serviceDefinition/',
    'tag': '/api/tags/tag/',
    'tag_configuration': '/api/tags/tagConfiguration/',
    'tag_group': '/api/tags/tagGroup/',
    'task' : '/api/task/task/',
    'task_break_limit' : '/api/task/taskBreakLimitType/',
    'task_creation_strat' : '/api/task/taskCreationStrategy/',
    'task_creation_template' : '/api/task/taskCreationTemplate/',
    'task_detail':'/api/task/taskDetail/',
    'transactions' : '/api/task/transaction/',
    'transformer_template' : '/api/transformer/transformerTemplate/',
    'user_defined_relationship': '/api/standardconfig/userDefinedRelationShip/',
}

common_search_services = {
    'search_entities_metadata':'/api/fwcore/entities/metadata/listMetadata/allEntities',
    'search_job_type_def': '/api/batch/jobTypeDefinition/search',
    'search_log_level' : '/api/logCategory/logLevel/search',
    'search_message_log_level' : '/api/errorHandler/messageLogLevel/search',
    'search_processed_message':'/api/ServiceDefinition/processedMessage/search',
    'search_task_status' : '/api/task/taskStatus/search',
    'search_task_detail_status' : '/api/task/taskDetailStatus/search',
}

common_get_services = {
    'get_env' : '/env',
    'get_all_entities_metadata': '/api/fwcore/entities/metadata/listMetadata/allEntities',
    'get_asciidoc': '/api/asciidoc',
    'get_entities_metadata': '/api/fwcore/entities/metadata',
    'get_extended_attr_history': '/api/fwcore/extendedAttributesHistory',
    'get_feature_flags': '/internal/feature-flags/features/all',
    'get_job_type': '/api/batch/getJobTypes',
    'get_job_type_def': '/api/batch/getJobTypeDefinitions',
    'get_languages': '/api/fw/localization/languages/',
    'get_supported_languages': '/api/fw/localization/supported/languages/',
    'get_supported_locales': '/api/fw/localization/locales/',
    'get_log_level' : '/api/logCategory/logLevel',
    'get_mapping_doparent_entity_names' : '/api/fwcore/interfaceDoc/entities',
    'get_message_log_level' : '/api/errorHandler/messageLogLevel',
    'get_task_status' : '/api/task/taskStatus/',
    'get_task_detail_status' : '/api/task/taskDetailStatus/',
}

common_import_services = {
    'trigger_job': '/api/batch/jobSchedule/trigger',
}


