general_services = {
    'activities': '/lmcore/api/lmcore/activity/',
    'adjusted_events': '/lmcore/api/lmcore/adjustmentSummaryDetail/',
    'adjusted_time_ranges': '/lmcore/api/lmcore/adjustmentSummary/',
    'adjustment_codes': '/lmcore/api/lmcore/eventAdjustmentCode/',
    'audit_logs': '/lmcore/api/lmcore/auditLog/',
    'available_attribute':'/lmcore/api/lmcore/availableAttribute/',
    'category_mapping':'/lmcore/api/lmcore/categoryMapping/',
    'challenge_progress': '/lmincentivepay/api/lmincentivepay/employeeChallengeProgress/',
    'console_by_employee_day_id':'/lmcore/api/lmcore/consoleByEmployeeDayId/',
    'consolidated_events': '/lmcore/api/lmcore/eventConsolidation/',
    'dynamic_activity_strategies': '/lmcore/api/lmcore/dynamicActivityStrategy/',
    'element_strategies': '/lmcore/api/lmcore/elementStrategy/',
    'elements': '/lmcore/api/lmcore/elements/',
    'employee_days': '/lmcore/api/lmcore/employeeDay/',
    'employee_pay_records': '/lmincentivepay/api/lmincentivepay/employeePay/',
    'employee_reflective_assignments': '/lmcore/api/lmcore/employeeReflectiveAssign/',
    'employee_statuses': '/lmcore/api/lmcore/employeeStatus/',
    'employee_training_curves': '/lmcore/api/lmcore/employeeTrainingCurve/',
    'employee_types': '/lmcore/api/lmcore/employeeType/',
    'error_logs': '/lmcore/api/lmcore/errorLog/',
    'event_approvals': '/lmcore/api/lmcore/eventApprovals/',
    'event_category_attribute':'/lmcore/api/lmcore/eventCategoryAttribute/',
    'event_consolidation':'/lmcore/api/lmcore/eventConsolidation/',
    'events': '/lmcore/api/lmcore/eventSummaryHeader/',
    'facility_parameters': '/lmcore/api/lmcore/facilityConfigData/',
    'forecast_output':'/lmcore/api/lmcore/forecastOutput/',
    'groups': '/lmcore/api/lmcore/group/',
    'handling_attribute_assignments': '/lmcore/api/lmcore/handlingAttrAssign/',
    'handling_attributes': '/lmcore/api/lmcore/handlingAttribute/',
    'hierarchies': '/lmcore/api/lmcore/hierarchy/',
    'indirect_activities': '/lmcore/api/lmcore/activityIndirect/',
    'interim_punches': '/lmcore/api/lmcore/interimPunches/',
    'labor_estimates': '/lmcore/api/lmcore/laborEstimate/',
    'labor_messages': '/lmcore/api/lmcore/laborMessage/',
    'labor_supply':'/lmcore/api/lmcore/laborSupply/',
    'location_handling_attributes': '/lmcore/api/lmcore/locationHandlingAttr/',
    'pfd_codes': '/lmcore/api/lmcore/pfdCodes/',
    'punch_cards': '/lmcore/api/lmcore/punchCard/',
    'quality_audit_data_entry': '/lmcore/api/lmcore/qualityAudit/',
    'safety_incidents': '/lmcore/api/lmcore/safetyIncident/',
    'scheduled_events': '/lmcore/api/lmcore/scheduledEvent/',
    'scheduled_group_assignments': '/lmcore/api/lmcore/groupAssignmentSchedule/',
    'shifts': '/lmcore/api/lmcore/shift/',
    'throughput_rate_history':'/lmcore/api/lmcore/throughputRateHistory/',
    'training_groups': '/lmcore/api/lmcore/trainingGroup/',
    'transition_groups': '/lmcore/api/lmcore/transitionGroup/',
    'vehicle_types': '/lmcore/api/lmcore/vehicleType/',
    'vehicles': '/lmcore/api/lmcore/vehicle/',
}

search_services = {}
get_services = {}