log_services = {
    'set_common_facade_logs': f'/commonui-facade/component/logger/com.manh.cp.commonui-facade/',
    'set_cubing_logs': f'/cubing/component/logger/com.manh.cp.cubing/',
    'set_dcallocation_logs': f'/dcallocation/component/logger/com.manh.cp.dcallocation/',
    'set_dcconsolidation_logs': f'/dcconsolidation/component/logger/com.manh.cp.dcconsolidation/',
    'set_dcinventory_logs': f'/dcinventory/component/logger/com.manh.cp.dcinventory/',
    'set_dcshipping_logs': f'/dcshipping/component/logger/com.manh.cp.dcshipping/',
    'set_inventory_management_logs': f'/inventory-management/component/logger/com.manh.cp.inventory-management/',
    'set_item_master_logs': f'/item-master/component/logger/com.manh.cp.item-master/',
    'set_lm_logs': f'/lmcore/component/logger/com.manh.cp.lmcore/',
    'set_lpn_disposition_logs': f'/lpn-disposition/component/logger/com.manh.cp.lpn-disposition/',
    'set_order_logs': f'/dcorder/component/logger/com.manh.cp.dcorder/',
    'set_organization_logs': f'/organization/component/logger/com.manh.cp.organization/',
    'set_pick_pack_logs': f'/pickpack/component/logger/com.manh.cp.pickpack/',
    'set_pix_logs': f'/pix/component/logger/com.manh.cp.pix/',
    'set_putaway_logs': f'/putaway/component/logger/com.manh.cp.putaway/',
    'set_receiving_logs': f'/receiving/component/logger/com.manh.cp.receiving/',
    'set_routing_logs': f'/routing/component/logger/com.manh.cp.routing/',
    'set_shipconfirm_logs': f'/shipconfirm/component/logger/com.manh.cp.shipconfirm/',
    'set_shipment_logs': f'/shipment/component/logger/com.manh.cp.shipment/',
    'set_task_logs': f'/task/component/logger/com.manh.cp.task/',
    'set_workrelease_logs': f'/workrelease/component/logger/com.manh.cp.workrelease/',
    'set_ym_logs': f'/yard-management/component/logger/com.manh.cp.yard-management/',
}